export enum SerialMessage {
  POWER = 'POWER',
  STOP = 'FUNC/STOP',
  VOLUME_PLUS = 'VOL+',
  VOLUME_MINUS = 'VOL-',
  FAST_BACK = 'FAST BACK',
  FAST_FORWARD = 'FAST FORWARD',
  PAUSE = 'PAUSE',
  DOWN = 'DOWN',
  UP = 'UP',
  EQUAL = 'EQ',
  REPEAT = 'ST/REPT',
  ZERO = '0',
  ONE = '1',
  TWO = '2',
  THREE = '3',
  FOUR = '4',
  FIVE = '5',
  SIX = '6',
  SEVEN = '7',
  EIGHT = '8',
  NINE = '9'
}
